import { Role } from "../user.interface";

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",

  USER_VIEW: "user:view",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_RESTORE: "user:restore",
  USER_ROLE_UPDATE: "user:role:update",
  USER_STATUS_UPDATE: "user:status:update",
  USER_PERMISSION_UPDATE: "user:permission:update",

  LEAD_VIEW: "lead:view",
  LEAD_CREATE: "lead:create",
  LEAD_UPDATE: "lead:update",
  LEAD_DELETE: "lead:delete",
  LEAD_ASSIGN: "lead:assign",
  LEAD_CONVERT: "lead:convert",
  CLIENT_VIEW: "client:view",
  CLIENT_CREATE: "client:create",
  CLIENT_UPDATE: "client:update",
  CLIENT_DELETE: "client:delete",

  PROJECT_VIEW: "project:view",
  PROJECT_CREATE: "project:create",
  PROJECT_UPDATE: "project:update",
  PROJECT_DELETE: "project:delete",

  TASK_VIEW: "task:view",
  TASK_CREATE: "task:create",
  TASK_UPDATE: "task:update",
  TASK_DELETE: "task:delete",
  TASK_ASSIGN: "task:assign",

  CALENDAR_VIEW: "calendar:view",
  CALENDAR_MANAGE: "calendar:manage",
  MEETING_VIEW: "meeting:view",
  MEETING_CREATE: "meeting:create",
  MEETING_UPDATE: "meeting:update",
  MEETING_DELETE: "meeting:delete",

  FILE_VIEW: "file:view",
  FILE_UPLOAD: "file:upload",
  FILE_DELETE: "file:delete",

  HR_VIEW: "hr:view",
  HR_MANAGE: "hr:manage",

  FINANCE_VIEW: "finance:view",
  FINANCE_MANAGE: "finance:manage",

  REPORT_VIEW: "report:view",

  CMS_VIEW: "cms:view",
  CMS_MANAGE: "cms:manage",

  SETTINGS_VIEW: "settings:view",
  SETTINGS_MANAGE: "settings:manage",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];


const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: ALL_PERMISSIONS,

  [Role.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_RESTORE,
    PERMISSIONS.USER_ROLE_UPDATE,
    PERMISSIONS.USER_STATUS_UPDATE,
    PERMISSIONS.USER_PERMISSION_UPDATE,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_CONVERT,

    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CLIENT_DELETE,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_ASSIGN,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.MEETING_VIEW,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.MEETING_DELETE,

    PERMISSIONS.FILE_VIEW,
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_DELETE,

    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_MANAGE,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.CMS_VIEW,
    PERMISSIONS.CMS_MANAGE,

    PERMISSIONS.SETTINGS_VIEW,
  ],

  [Role.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_CONVERT,

    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_UPDATE,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.MEETING_VIEW,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_UPDATE,

    PERMISSIONS.FILE_VIEW,
    PERMISSIONS.FILE_UPLOAD,

    PERMISSIONS.REPORT_VIEW,
  ],

  [Role.DEVELOPER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_UPDATE,

    PERMISSIONS.FILE_VIEW,
    PERMISSIONS.FILE_UPLOAD,

    PERMISSIONS.CALENDAR_VIEW,

    PERMISSIONS.MEETING_VIEW,
  ],

  [Role.DESIGNER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_UPDATE,

    PERMISSIONS.FILE_VIEW,
    PERMISSIONS.FILE_UPLOAD,

    PERMISSIONS.CALENDAR_VIEW,

    PERMISSIONS.MEETING_VIEW,
  ],

  [Role.MARKETER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,

    PERMISSIONS.CLIENT_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.FILE_VIEW,
    PERMISSIONS.FILE_UPLOAD,

    PERMISSIONS.CALENDAR_VIEW,

    PERMISSIONS.MEETING_VIEW,
  ],

  [Role.STAFF]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.TASK_VIEW,

    PERMISSIONS.CALENDAR_VIEW,

    PERMISSIONS.MEETING_VIEW,
  ],
};